name: PlacelessShulkerbox
version: beta-1.2
main: tgcdev.psbox.PluginMain
author: tagucha
website: https://github.com/tagucha/PlacelessShulkerbox
permissions:
  psbox.open:
    description: To use the function.
    default: true