name: PlacelessShulkerbox
version: beta-1.1
main: tgcdev.cos.PluginMain
author: tagucha
website: https://github.com/tagucha/PlacelessShulkerbox
permissions:
  cos.open:
    description: To use the function.
    default: true